global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['127.0.0.1:9093']
  - job_name: 'karma'
    static_configs:
      - targets: ['127.0.0.1:8080']
  - job_name: 'bank'
    static_configs:
      - targets: ['127.0.0.1:8081']

rule_files:
  - 'prometheus.alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '127.0.0.1:9093'
